[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; Portul se detecteaza automat. Daca ai mai multe dispozitive USB-serial,
; decomenteaza si pune portul tau (afla-l cu: pio device list)
; upload_port = COM5
; monitor_port = COM5
build_flags =
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
